version: '3.2'
services:
  database:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: main_database
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

      
  app:
    build: 
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy 
