version: '3.2'
services:
  database:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: main_database
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

      
  app:
    build: 
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy 
    environment:
      BASE_URL: "http://127.0.0.1:4000/api/v1"
      TOKEN: "token 3dc7c38c526c10676533e1262d6b75c7020a05b9"
    # command: -p 8000  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy 

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    expose:
    - "5431"
    ports:
      - "5431:5431"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    command: -p 5431

  server:
    image: gitea/gitea:1.21.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5431
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:3000"
      - "222:22"
    depends_on:
      - db
